routes/web.php
<?php

declare(strict_types=1);

// Métodos de envío
use Bittacora\Bpanel4\Shipping\FreeShipping\Http\Controllers\FreeShippingAdminController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel/envio')->name('bpanel4-shipping.free-shipping.bpanel.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function () {
        Route::get('/metodos-de-envio/FreeShipping/{zone}/crear', [FreeShippingAdminController::class, 'create'])->name('create');
        Route::post('/metodos-de-envio/FreeShipping/{zone}/crear', [FreeShippingAdminController::class, 'store'])->name('store');
        Route::get('/metodos-de-envio/FreeShipping/{model}/editar', [FreeShippingAdminController::class, 'edit'])->name('edit');
        Route::post('/metodos-de-envio/FreeShipping/{model}/editar', [FreeShippingAdminController::class, 'update'])->name('update');
        Route::delete('/metodos-de-envio/FreeShipping/{model}/eliminar', [FreeShippingAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/_form.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-free-shipping::form.new-product'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ $panelTitle }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
            @csrf
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('bpanel4-free-shipping::form.name'), 'required'=>true, 'value' => old('name') ?? $model?->getName() ])
            @livewire('form::input-number', [
                'name' => 'minimum_order_amount',
                'labelText' => __('bpanel4-free-shipping::form.minimum_order_amount'),
                'required'=>true,
                'value' => old('minimum_order_amount') ?? $model?->getMinimumOrderAmount()->toFloat() ?? 0,
                'min' => 0,
                'step' => 0.01,
                'fieldWidth' => 7,
                'labelWidth' => 3
            ])
            @livewire('form::input-checkbox', [
                'name' => 'active',
                'value' => 1,
                'checked' => $model?->isActive() ?? false,
                'labelText' => __('bpanel4-shipping::form.active'), 'bpanelForm' => true
            ])
            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @if (null !== $model)
                <input type="hidden" name="id" value="{{ $model->getId() }}">
                <input type="hidden" name="shipping_zone_id" value="{{ $model->getShippingZoneId() }}">
            @else
                <input type="hidden" name="shipping_zone_id" value="{{ $zone->getId() }}">
            @endif
        </form>
        @if($errors->any())
            {{ implode('', $errors->all('<div>:message</div>')) }}
        @endif
    </div>

@endsection

resources/views/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-free-shipping::form.create-free-shipping'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-free-shipping::form.create-free-shipping') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-shipping.free-shipping.bpanel.store', [
            'zone' => $zone,
            'model' => $model,
        ])}}">
            @include('bpanel4-free-shipping::bpanel._form', ['panelTitle' => __('bpanel4-free-shipping::form.create-free-shipping')])
        </form>
    </div>

@endsection

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-free-shipping::form.edit-free-shipping'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-free-shipping::form.edit-free-shipping') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-shipping.free-shipping.bpanel.update', [
            'model' => $model,
        ])}}">
            @include('bpanel4-free-shipping::bpanel._form', ['panelTitle' => __('bpanel4-free-shipping::form.edit-free-shipping')])
        </form>
    </div>

@endsection